digits:
  length_1: 1
  length_6: 6
  length_30: 30
  length_50: 50
  length_255: 255
  length_200: 200
  length_1000: 1000
email:
  regex: !ruby/regexp '/\A[\w+-.]+@[a-z\d-]+(.[a-z\d-]+)*.[a-z]+\z/i'
date:
  format: "%d/%m/%Y"
  format_date_field: "%Y-%m-%d"
  format_month_field: "%Y-%m"
pagy:
  number_items: 8
  number_items_10: 10
project:
  max_length_200: 200
  max_length_1000: 1000
user_roles:
  manager: "manager"
  admin: "admin"
project_roles:
  PSM: "PSM"
number:
  value_100: 100
  value_0: 0