digits:
  length_1: 1
  length_2: 2
  length_6: 6
  length_12: 12
  length_30: 30
  length_50: 50
  length_255: 255
  length_200: 200
  length_1000: 1000
  length_3000: 3000
email:
  regex: !ruby/regexp '/\A[\w+-.]+@[a-z\d-]+(.[a-z\d-]+)*.[a-z]+\z/i'
date:
  format: "%d/%m/%Y"
  format_date_field: "%Y-%m-%d"
  format_month_field: "%Y-%m"
pagy:
  number_items_10: 10
  number_items_20: 20
project:
  max_length_100: 100
  max_length_200: 200
  max_length_1000: 1000
user_roles:
  manager: "manager"
  admin: "admin"
project_roles:
  PSM: "PSM"
number:
  value_100: 100
  value_0: 0
month_year:
  regex: !ruby/regexp '/\A\d{4}-(0[1-9]|1[0-2])\z/'
check_destroy:
  destroy_true: "1"
  destroy_false: "false"
is_released:
  released: "released"
  preparing: "preparing"
